--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IPBANLIST
--------------------------------------------------------

  CREATE TABLE "IPBANLIST" 
   (	"USERID" VARCHAR2(20), 
	"IP" VARCHAR2(20), 
	"BANDATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
REM INSERTING into IPBANLIST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index IPBANLIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IPBANLIST_PK" ON "IPBANLIST" ("USERID", "IP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  Constraints for Table IPBANLIST
--------------------------------------------------------

  ALTER TABLE "IPBANLIST" ADD CONSTRAINT "IPBANLIST_PK" PRIMARY KEY ("USERID", "IP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
 
  ALTER TABLE "IPBANLIST" MODIFY ("USERID" NOT NULL ENABLE)
 
  ALTER TABLE "IPBANLIST" MODIFY ("IP" NOT NULL ENABLE)
 
  ALTER TABLE "IPBANLIST" MODIFY ("BANDATE" NOT NULL ENABLE)
 
  ALTER TABLE "IPBANLIST" MODIFY ("ENABLED" NOT NULL ENABLE)
